# CCC y Adam
services:
  nodered:
    build: .
    image: xchanger_nodered:latest
    container_name: xchanger_nodered
    ports:
      - "32880:1880"
    volumes:
      - ./nodered_data:/data
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: xchanger_postgres
    environment:
      POSTGRES_USER: xchauser
      POSTGRES_PASSWORD: xchapass
      POSTGRES_DB: xchadb
    ports:
      - "55432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped